apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory    # link to Let's Encrypt's production server
    email: 'zarres2000@gmail.com'    # LE requires email
    privateKeySecretRef:
      name: letsencrypt-prod        # where to put secret key that LE will use for authentication (this is different from Certificate Secret!!!)
    http01: {}                      # use http version of communication with LE (there is also DNS version)